import { Inter } from 'next/font/google'
import './globals.css'
import Wrapper from './components/Wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Search Hacker News.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <Wrapper>
        {children}
        </Wrapper>
      </body>
    </html>
  )
}
